### ISSUE TITLE
IOError: [Errno ftp error] [Errno 111] Connection refused

### ISSUE THREAD

**Issue by nivetaiyer** [MarvinTeichmann/KittiSeg#104]
I'm trying to download the kitti dataset as in step 2 by invoking this command:
python download_data.py --kitti_url MY_URL
MY_URL is replaced by the link I get in my email. I however get this error:

2017-08-02 11:43:00,514 INFO Downloading VGG weights.
2017-08-02 11:43:00,514 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy
2017-08-02 11:43:00,514 INFO Download DIR: DATA
Traceback (most recent call last):
  File "download_data.py", line 143, in <module>
    main()
  File "download_data.py", line 96, in main
    download(vgg_url, data_dir)
  File "download_data.py", line 73, in download
    reporthook=_progress)
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 550, in open_ftp
    ftpwrapper(user, passwd, host, port, dirs)
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 877, in __init__
    self.init()
  File "/home/niyer2/anaconda2/lib/python2.7/urllib.py", line 886, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/niyer2/anaconda2/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/home/niyer2/anaconda2/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno ftp error] [Errno 111] Connection refused

Any advise?

**Comment by MarvinTeichmann** [comment]
Try again later. The server has high loads at some times.
