### ISSUE TITLE
 Python3.x to run the KittiSeg/kittibox code

### ISSUE THREAD

**Issue by qoo** [MarvinTeichmann/KittiSeg#105]
INFO:tensorflow:Restoring parameters from RUNS/KittiBox_pretrained/model.ckpt-179999
2017-08-01 21:09:32,745 INFO Restoring parameters from RUNS/KittiBox_pretrained/model.ckpt-179999
2017-08-01 21:09:34,871 INFO Weights loaded successfully.
2017-08-01 21:09:34,871 INFO Starting inference using data/demo.png as input
Traceback (most recent call last):
  File "demo.py", line 219, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 175, in main
    min_conf=0.50, tau=hypes['tau'], color_acc=(0, 255, 0))
  File "incl/utils/train_utils.py", line 103, in add_rectangles
    from utils.stitch_wrapper import stitch_rects
ImportError: incl/utils/stitch_wrapper.so: undefined symbol: _Py_ZeroStruct

I followed this post:
https://github.com/MarvinTeichmann/KittiSeg/issues/36

https://github.com/MarvinTeichmann/KittiBox/tree/5ec5681981aa050a8c0e4d5853db50a6b5257e2a
May I ask that which version works for python 3.5? Thanks a lot.

**Comment by GeorgiAngelov** [comment]
Try running **make all-python3** from inside submodules/utils/
