### ISSUE TITLE
tv-continue raises "ValueError: No variables provided."

### ISSUE THREAD

**Issue by kalanityL** [MarvinTeichmann/KittiSeg#111]
Hi, 
I followed https://github.com/MarvinTeichmann/KittiSeg/issues/56 to train from a pretrained model. 

First I did a test training of 40 iterations (by changing hypes/Kittyseg.json solver->max_steps to 40).

I renamed this training into KittiSeg_test_40_iter in the RUNS folder. 

then updated the RUNS/KittiSeg_test_40_iter/model_files/hypes.json solver->max_steps to 60. 

And then tried  tv-continue --logdir RUNS/KittiSeg_test_40_iter/

I got the following error: 

`  File "/home/kalanit/.local/bin/tv-continue", line 53, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/kalanit/.local/bin/tv-continue", line 49, in main
    train.continue_training(FLAGS.logdir)
  File "/home/kalanit/.local/lib/python3.5/site-packages/tensorvision/train.py", line 425, in continue_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "/home/kalanit/.local/lib/python3.5/site-packages/tensorvision/core.py", line 100, in build_training_graph
    global_step, learning_rate)
  File "RUNS/KittiSeg_test_40_iter/model_files/solver.py", line 91, in training
    global_step=global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 423, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.`

Anyone had the same issue?
Any idea why and/or how to solve it? .. 

Thanks
K.

**Comment by kalanityL** [comment]
Full output of the command: 

`2017-08-13 13:12:38,560 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/kalanit/tv-plugins'.
2017-08-13 13:12:38,560 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-08-13 13:12:38,560 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-08-13 13:12:38,560 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-08-13 13:12:38,560 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-08-13 13:12:38,560 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-08-13 13:12:38,561 INFO Starting to analyze model in 'RUNS/KittiSeg_test_40_iter/'
2017-08-13 13:12:38,561 INFO f: <_io.TextIOWrapper name='RUNS/KittiSeg_test_40_iter/model_files/hypes.json' mode='r' encoding='UTF-8'>
2017-08-13 13:12:38.563557: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-13 13:12:38.563571: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-13 13:12:38.563575: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-13 13:12:38.563578: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-13 13:12:38.563582: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-13 13:12:40.408290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:03:00.0
Total memory: 10.91GiB
Free memory: 10.76GiB
2017-08-13 13:12:40.408316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-08-13 13:12:40.408323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-08-13 13:12:40.408334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)
npy file loaded
Layer name: conv1_1
Layer shape: (3, 3, 3, 64)
2017-08-13 13:12:40,850 INFO Creating Summary for: conv1_1/filter
2017-08-13 13:12:40,863 INFO Creating Summary for: conv1_1/biases
Layer name: conv1_2
Layer shape: (3, 3, 64, 64)
2017-08-13 13:12:40,878 INFO Creating Summary for: conv1_2/filter
2017-08-13 13:12:40,890 INFO Creating Summary for: conv1_2/biases
Layer name: conv2_1
Layer shape: (3, 3, 64, 128)
2017-08-13 13:12:40,907 INFO Creating Summary for: conv2_1/filter
2017-08-13 13:12:40,919 INFO Creating Summary for: conv2_1/biases
Layer name: conv2_2
Layer shape: (3, 3, 128, 128)
2017-08-13 13:12:40,935 INFO Creating Summary for: conv2_2/filter
2017-08-13 13:12:40,947 INFO Creating Summary for: conv2_2/biases
Layer name: conv3_1
Layer shape: (3, 3, 128, 256)
2017-08-13 13:12:40,964 INFO Creating Summary for: conv3_1/filter
2017-08-13 13:12:40,976 INFO Creating Summary for: conv3_1/biases
Layer name: conv3_2
Layer shape: (3, 3, 256, 256)
2017-08-13 13:12:40,993 INFO Creating Summary for: conv3_2/filter
2017-08-13 13:12:41,006 INFO Creating Summary for: conv3_2/biases
Layer name: conv3_3
Layer shape: (3, 3, 256, 256)
2017-08-13 13:12:41,023 INFO Creating Summary for: conv3_3/filter
2017-08-13 13:12:41,035 INFO Creating Summary for: conv3_3/biases
Layer name: conv4_1
Layer shape: (3, 3, 256, 512)
2017-08-13 13:12:41,054 INFO Creating Summary for: conv4_1/filter
2017-08-13 13:12:41,066 INFO Creating Summary for: conv4_1/biases
Layer name: conv4_2
Layer shape: (3, 3, 512, 512)
2017-08-13 13:12:41,090 INFO Creating Summary for: conv4_2/filter
2017-08-13 13:12:41,102 INFO Creating Summary for: conv4_2/biases
Layer name: conv4_3
Layer shape: (3, 3, 512, 512)
2017-08-13 13:12:41,122 INFO Creating Summary for: conv4_3/filter
2017-08-13 13:12:41,135 INFO Creating Summary for: conv4_3/biases
Layer name: conv5_1
Layer shape: (3, 3, 512, 512)
2017-08-13 13:12:41,155 INFO Creating Summary for: conv5_1/filter
2017-08-13 13:12:41,168 INFO Creating Summary for: conv5_1/biases
Layer name: conv5_2
Layer shape: (3, 3, 512, 512)
2017-08-13 13:12:41,189 INFO Creating Summary for: conv5_2/filter
2017-08-13 13:12:41,201 INFO Creating Summary for: conv5_2/biases
Layer name: conv5_3
Layer shape: (3, 3, 512, 512)
2017-08-13 13:12:41,221 INFO Creating Summary for: conv5_3/filter
2017-08-13 13:12:41,233 INFO Creating Summary for: conv5_3/biases
Layer name: fc6
Layer shape: [7, 7, 512, 4096]
2017-08-13 13:12:41,510 INFO Creating Summary for: fc6/weights
2017-08-13 13:12:41,523 INFO Creating Summary for: fc6/biases
Layer name: fc7
Layer shape: [1, 1, 4096, 4096]
2017-08-13 13:12:41,587 INFO Creating Summary for: fc7/weights
2017-08-13 13:12:41,599 INFO Creating Summary for: fc7/biases
2017-08-13 13:12:41,620 INFO Creating Summary for: score_fr/weights
2017-08-13 13:12:41,632 INFO Creating Summary for: score_fr/biases
2017-08-13 13:12:41,654 INFO Creating Summary for: upscore2/up_filter
2017-08-13 13:12:41,672 INFO Creating Summary for: score_pool4/weights
2017-08-13 13:12:41,684 INFO Creating Summary for: score_pool4/biases
2017-08-13 13:12:41,705 INFO Creating Summary for: upscore4/up_filter
2017-08-13 13:12:41,723 INFO Creating Summary for: score_pool3/weights
2017-08-13 13:12:41,735 INFO Creating Summary for: score_pool3/biases
2017-08-13 13:12:41,756 INFO Creating Summary for: upscore32/up_filter
Traceback (most recent call last):
  File "/home/kalanit/.local/bin/tv-continue", line 53, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/kalanit/.local/bin/tv-continue", line 49, in main
    train.continue_training(FLAGS.logdir)
  File "/home/kalanit/.local/lib/python3.5/site-packages/tensorvision/train.py", line 425, in continue_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "/home/kalanit/.local/lib/python3.5/site-packages/tensorvision/core.py", line 100, in build_training_graph
    global_step, learning_rate)
  File "RUNS/KittiSeg_test_40_iter/model_files/solver.py", line 91, in training
    global_step=global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 423, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.
`

**Comment by kalanityL** [comment]
sorry - duplicate for https://github.com/MarvinTeichmann/KittiSeg/issues/35
don't know how to delete this issue. Feel free to remove it 
Sorry again

**Comment by DetectionIIT** [comment]
Have you deleted this issue? please tell how
