### ISSUE TITLE
I have trouble in the 'demo.py'

### ISSUE THREAD

**Issue by hmyjanet** [MarvinTeichmann/KittiSeg#112]
Dear doctor Marvin Teichmann:
Thanks for your pretty good work and share. However, when I want to run your code, There are some problems. And I can't find the way to solve it. When I run the 'demo.py', the error message are as following:
`hmy@amax-1080:~/KittiSeg$ python demo.py --input_image data/demo/demo.png
2017-08-16 22:08:23,010 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/hmy/tv-plugins'.
2017-08-16 22:08:23,010 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-08-16 22:08:23,011 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-08-16 22:08:23,011 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-08-16 22:08:23,011 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-08-16 22:08:23,011 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-08-16 22:08:23,011 INFO f: <open file 'RUNS/KittiSeg_pretrained/model_files/hypes.json', mode 'r' at 0x7f5e319c7780>
2017-08-16 22:08:23,012 INFO Hypes loaded successfully.
2017-08-16 22:08:23,012 INFO Modules loaded successfully. Starting to build tf graph.
npy file loaded
Layer name: conv1_1
Layer shape: (3, 3, 3, 64)
2017-08-16 22:08:23,439 INFO Creating Summary for: conv1_1/filter
2017-08-16 22:08:23,455 INFO Creating Summary for: conv1_1/biases
Layer name: conv1_2
Layer shape: (3, 3, 64, 64)
2017-08-16 22:08:23,517 INFO Creating Summary for: conv1_2/filter
2017-08-16 22:08:23,532 INFO Creating Summary for: conv1_2/biases
Layer name: conv2_1
Layer shape: (3, 3, 64, 128)
2017-08-16 22:08:23,552 INFO Creating Summary for: conv2_1/filter
2017-08-16 22:08:23,566 INFO Creating Summary for: conv2_1/biases
Layer name: conv2_2
Layer shape: (3, 3, 128, 128)
2017-08-16 22:08:23,586 INFO Creating Summary for: conv2_2/filter
2017-08-16 22:08:23,601 INFO Creating Summary for: conv2_2/biases
Layer name: conv3_1
Layer shape: (3, 3, 128, 256)
2017-08-16 22:08:23,621 INFO Creating Summary for: conv3_1/filter
2017-08-16 22:08:23,636 INFO Creating Summary for: conv3_1/biases
Layer name: conv3_2
Layer shape: (3, 3, 256, 256)
2017-08-16 22:08:23,656 INFO Creating Summary for: conv3_2/filter
2017-08-16 22:08:23,671 INFO Creating Summary for: conv3_2/biases
Layer name: conv3_3
Layer shape: (3, 3, 256, 256)
2017-08-16 22:08:23,692 INFO Creating Summary for: conv3_3/filter
2017-08-16 22:08:23,707 INFO Creating Summary for: conv3_3/biases
Layer name: conv4_1
Layer shape: (3, 3, 256, 512)
2017-08-16 22:08:23,728 INFO Creating Summary for: conv4_1/filter
2017-08-16 22:08:23,743 INFO Creating Summary for: conv4_1/biases
Layer name: conv4_2
Layer shape: (3, 3, 512, 512)
2017-08-16 22:08:23,774 INFO Creating Summary for: conv4_2/filter
2017-08-16 22:08:23,790 INFO Creating Summary for: conv4_2/biases
Layer name: conv4_3
Layer shape: (3, 3, 512, 512)
2017-08-16 22:08:23,820 INFO Creating Summary for: conv4_3/filter
2017-08-16 22:08:23,835 INFO Creating Summary for: conv4_3/biases
Layer name: conv5_1
Layer shape: (3, 3, 512, 512)
2017-08-16 22:08:23,861 INFO Creating Summary for: conv5_1/filter
2017-08-16 22:08:23,876 INFO Creating Summary for: conv5_1/biases
Layer name: conv5_2
Layer shape: (3, 3, 512, 512)
2017-08-16 22:08:23,902 INFO Creating Summary for: conv5_2/filter
2017-08-16 22:08:23,917 INFO Creating Summary for: conv5_2/biases
Layer name: conv5_3
Layer shape: (3, 3, 512, 512)
2017-08-16 22:08:23,943 INFO Creating Summary for: conv5_3/filter
2017-08-16 22:08:23,958 INFO Creating Summary for: conv5_3/biases
Layer name: fc6
Layer shape: [7, 7, 512, 4096]
2017-08-16 22:08:24,408 INFO Creating Summary for: fc6/weights
2017-08-16 22:08:24,423 INFO Creating Summary for: fc6/biases
Layer name: fc7
Layer shape: [1, 1, 4096, 4096]
2017-08-16 22:08:24,515 INFO Creating Summary for: fc7/weights
2017-08-16 22:08:24,530 INFO Creating Summary for: fc7/biases
2017-08-16 22:08:24,552 INFO Creating Summary for: score_fr/weights
2017-08-16 22:08:24,567 INFO Creating Summary for: score_fr/biases
2017-08-16 22:08:24,595 INFO Creating Summary for: upscore2/up_filter
2017-08-16 22:08:24,616 INFO Creating Summary for: score_pool4/weights
2017-08-16 22:08:24,631 INFO Creating Summary for: score_pool4/biases
2017-08-16 22:08:24,658 INFO Creating Summary for: upscore4/up_filter
2017-08-16 22:08:24,682 INFO Creating Summary for: score_pool3/weights
2017-08-16 22:08:24,697 INFO Creating Summary for: score_pool3/biases
2017-08-16 22:08:24,725 INFO Creating Summary for: upscore32/up_filter
2017-08-16 22:08:24,746 INFO Graph build successfully.
2017-08-16 22:08:24.747092: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-16 22:08:24.747112: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-16 22:08:24.747120: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-16 22:08:24.747128: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-16 22:08:24.747139: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-16 22:08:28.131747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2017-08-16 22:08:28.131879: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x234d3f0
2017-08-16 22:08:28.422723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 1 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:03:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2017-08-16 22:08:28.422850: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x47b9da0
2017-08-16 22:08:28.729989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 2 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:82:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2017-08-16 22:08:28.730180: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x47bda30
2017-08-16 22:08:29.028832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 3 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:83:00.0
Total memory: 7.92GiB
Free memory: 7.81GiB
2017-08-16 22:08:29.030224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 0 and 2
2017-08-16 22:08:29.030255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 0 and 3
2017-08-16 22:08:29.030286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 1 and 2
2017-08-16 22:08:29.030306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 1 and 3
2017-08-16 22:08:29.030321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 2 and 0
2017-08-16 22:08:29.030336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 2 and 1
2017-08-16 22:08:29.031314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 3 and 0
2017-08-16 22:08:29.031341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 3 and 1
2017-08-16 22:08:29.031423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 1 2 3 
2017-08-16 22:08:29.031439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y Y N N 
2017-08-16 22:08:29.031449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 1:   Y Y N N 
2017-08-16 22:08:29.031459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 2:   N N Y Y 
2017-08-16 22:08:29.031469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 3:   N N Y Y 
2017-08-16 22:08:29.031492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
2017-08-16 22:08:29.031512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
2017-08-16 22:08:29.031612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX 1080, pci bus id: 0000:82:00.0)
2017-08-16 22:08:29.031665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX 1080, pci bus id: 0000:83:00.0)
2017-08-16 22:08:29,351 INFO Weights loaded successfully.
2017-08-16 22:08:29,351 INFO Starting inference using data/demo/demo.png as input
Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    tf.app.run()
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 176, in main
    output = sess.run([softmax], feed_dict=feed)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value conv1_1/filter
	 [[Node: conv1_1/filter/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_1/filter"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_1/filter)]]
	 [[Node: Validation/decoder/Softmax/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_42_Validation/decoder/Softmax", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'conv1_1/filter/read', defined at:
  File "demo.py", line 228, in <module>
    tf.app.run()
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 148, in main
    image=image)
  File "incl/tensorvision/core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS/KittiSeg_pretrained/model_files/architecture.py", line 27, in inference
    vgg_fcn.build(images, train=train, num_classes=2, random_init_fc8=True)
  File "/home/hmy/KittiSeg/incl/tensorflow_fcn/fcn8_vgg.py", line 74, in build
    self.conv1_1 = self._conv_layer(bgr, "conv1_1")
  File "/home/hmy/KittiSeg/incl/tensorflow_fcn/fcn8_vgg.py", line 154, in _conv_layer
    filt = self.get_conv_filter(name)
  File "/home/hmy/KittiSeg/incl/tensorflow_fcn/fcn8_vgg.py", line 286, in get_conv_filter
    var = tf.get_variable(name="filter", initializer=init, shape=shape)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 714, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 316, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/hmy/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv1_1/filter
	 [[Node: conv1_1/filter/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_1/filter"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_1/filter)]]
	 [[Node: Validation/decoder/Softmax/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_42_Validation/decoder/Softmax", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`
Thanks~

**Comment by Bangseongdeok** [comment]
I had a same problem when trying to run the model learned from my data

**Comment by StuvX** [comment]
OK - so my particular problem is that I trained the model on one machine, and then copied it to my other machine, but when you do that the path definitions in the logdir checkpoint record doesn't necessarily point to the right location... I fixed it by updating the paths to the checkpoints and now it works on both machines. I hope that helps anybody else with the same issue.

**Comment by SpyderLord** [comment]
I'm confused as well.I have no idea how to organize my code.Any help will be appreciated~
