### ISSUE TITLE
Inference problem in Resnet50

### ISSUE THREAD

**Issue by chamcham115** [MarvinTeichmann/KittiSeg#124]
I trained the Resnet50. 
And I try to inference the trained network. 
But I got the error. 
Do you know what is the problem?
Is it problem for shape of tf value?

2017-09-19 11:35:45,128 INFO Modules loaded successfully. Starting to build tf graph.
Traceback (most recent call last):
  File "demo.py", line 229, in <module>
    tf.app.run()
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 149, in main
    image=image)
  File "incl/tensorvision/core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS/KittiSeg/KittiSeg_ResNet50_Lane_2017_09_15_16.31/model_files/architecture.py", line 72, in inference
    x = _conv(x, 64, ksize=7, stride=2)
  File "RUNS/KittiSeg/KittiSeg_ResNet50_Lane_2017_09_15_16.31/model_files/architecture.py", line 319, in _conv
    weight_decay=CONV_WEIGHT_DECAY)
  File "RUNS/KittiSeg/KittiSeg_ResNet50_Lane_2017_09_15_16.31/model_files/architecture.py", line 308, in _get_variable
    trainable=trainable)
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/eva00/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 685, in _get_single_variable
    "but instead was %s." % (name, shape))
ValueError: Shape of a new variable (scale1/weights) must be fully defined, but instead was (7, 7, ?, 64).

**Comment by chamcham115** [comment]
I got it. 
It can solve the fixed demo.py code. 
Add the shape in placeholder.

**Comment by John1231983** [comment]
Hi. How did you solve it? This is original code
```
       image_pl = tf.placeholder(tf.float32)
        image = tf.expand_dims(image_pl, 0)
```
Thanks

**Comment by lxyhahaha** [comment]
Hi, I also got this error, could you tell me how to fix it?

**Comment by ficha-ishida** [comment]
To fix this, add the shape to the tf.placeholder:
     
```
image_pl = tf.placeholder(tf.float32, shape=(h,w,3))
```
where h, w and 3 are the height, width and channels of the input image respectively.
