### ISSUE TITLE
run the train.py i got ValueError: No variables provided.

### ISSUE THREAD

**Issue by yxandam** [MarvinTeichmann/KittiSeg#130]
win10 64 python3.6
run
`C:\ProgramData\Anaconda3\python.exe D:/tf_fcn/KittiSeg/train.py --hypes hypes/KittiSeg_VGG.json`

got

`
2017-10-13 13:58:59,934 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to 'C:\Users\FD/tv-plugins'.
2017-10-13 13:58:59,934 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-10-13 13:58:59,934 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-10-13 13:58:59,934 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-10-13 13:58:59,934 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-10-13 13:58:59,934 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-10-13 13:59:00,008 INFO f: <_io.TextIOWrapper name='hypes/KittiSeg_VGG.json' mode='r' encoding='cp936'>
2017-10-13 13:59:00,011 INFO Initialize training folder
2017-10-13 13:59:00,078 INFO Start training
2017-10-13 13:59:00.096567: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 13:59:00.096881: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 13:59:00.711207: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce 840M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-10-13 13:59:00.711520: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017-10-13 13:59:00.711675: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y 
2017-10-13 13:59:00.711854: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 840M, pci bus id: 0000:01:00.0)
npy file loaded
Layer name: conv1_1
Layer shape: (3, 3, 3, 64)
2017-10-13 13:59:01,929 INFO Creating Summary for: conv1_1/filter
2017-10-13 13:59:01,957 INFO Creating Summary for: conv1_1/biases
Layer name: conv1_2
Layer shape: (3, 3, 64, 64)
2017-10-13 13:59:01,994 INFO Creating Summary for: conv1_2/filter
2017-10-13 13:59:02,023 INFO Creating Summary for: conv1_2/biases
Layer name: conv2_1
Layer shape: (3, 3, 64, 128)
2017-10-13 13:59:02,060 INFO Creating Summary for: conv2_1/filter
2017-10-13 13:59:02,089 INFO Creating Summary for: conv2_1/biases
Layer name: conv2_2
Layer shape: (3, 3, 128, 128)
2017-10-13 13:59:02,136 INFO Creating Summary for: conv2_2/filter
2017-10-13 13:59:02,169 INFO Creating Summary for: conv2_2/biases
Layer name: conv3_1
Layer shape: (3, 3, 128, 256)
2017-10-13 13:59:02,221 INFO Creating Summary for: conv3_1/filter
2017-10-13 13:59:02,255 INFO Creating Summary for: conv3_1/biases
Layer name: conv3_2
Layer shape: (3, 3, 256, 256)
2017-10-13 13:59:02,302 INFO Creating Summary for: conv3_2/filter
2017-10-13 13:59:02,334 INFO Creating Summary for: conv3_2/biases
Layer name: conv3_3
Layer shape: (3, 3, 256, 256)
2017-10-13 13:59:02,387 INFO Creating Summary for: conv3_3/filter
2017-10-13 13:59:02,431 INFO Creating Summary for: conv3_3/biases
Layer name: conv4_1
Layer shape: (3, 3, 256, 512)
2017-10-13 13:59:02,477 INFO Creating Summary for: conv4_1/filter
2017-10-13 13:59:02,506 INFO Creating Summary for: conv4_1/biases
Layer name: conv4_2
Layer shape: (3, 3, 512, 512)
2017-10-13 13:59:02,562 INFO Creating Summary for: conv4_2/filter
2017-10-13 13:59:02,596 INFO Creating Summary for: conv4_2/biases
Layer name: conv4_3
Layer shape: (3, 3, 512, 512)
2017-10-13 13:59:02,670 INFO Creating Summary for: conv4_3/filter
2017-10-13 13:59:02,699 INFO Creating Summary for: conv4_3/biases
Layer name: conv5_1
Layer shape: (3, 3, 512, 512)
2017-10-13 13:59:02,753 INFO Creating Summary for: conv5_1/filter
2017-10-13 13:59:02,796 INFO Creating Summary for: conv5_1/biases
Layer name: conv5_2
Layer shape: (3, 3, 512, 512)
2017-10-13 13:59:02,861 INFO Creating Summary for: conv5_2/filter
2017-10-13 13:59:02,891 INFO Creating Summary for: conv5_2/biases
Layer name: conv5_3
Layer shape: (3, 3, 512, 512)
2017-10-13 13:59:03,003 INFO Creating Summary for: conv5_3/filter
2017-10-13 13:59:03,036 INFO Creating Summary for: conv5_3/biases
Layer name: fc6
Layer shape: [7, 7, 512, 4096]
2017-10-13 13:59:03,491 INFO Creating Summary for: fc6/weights
2017-10-13 13:59:03,529 INFO Creating Summary for: fc6/biases
Layer name: fc7
Layer shape: [1, 1, 4096, 4096]
2017-10-13 13:59:03,645 INFO Creating Summary for: fc7/weights
2017-10-13 13:59:03,674 INFO Creating Summary for: fc7/biases
2017-10-13 13:59:03,734 INFO Creating Summary for: score_fr/weights
2017-10-13 13:59:03,770 INFO Creating Summary for: score_fr/biases
2017-10-13 13:59:04,015 WARNING From D:\tf_fcn\KittiSeg\tensorflow_fcn\fcn8_vgg.py:114: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From D:\tf_fcn\KittiSeg\tensorflow_fcn\fcn8_vgg.py:114: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2017-10-13 13:59:04,041 INFO Creating Summary for: upscore2/up_filter
2017-10-13 13:59:04,085 INFO Creating Summary for: score_pool4/weights
2017-10-13 13:59:04,115 INFO Creating Summary for: score_pool4/biases
2017-10-13 13:59:04,169 INFO Creating Summary for: upscore4/up_filter
2017-10-13 13:59:04,215 INFO Creating Summary for: score_pool3/weights
2017-10-13 13:59:04,253 INFO Creating Summary for: score_pool3/biases
2017-10-13 13:59:04,330 INFO Creating Summary for: upscore32/up_filter
WARNING:tensorflow:From D:\tf_fcn\KittiSeg\tensorflow_fcn\fcn8_vgg.py:140: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2017-10-13 13:59:04,368 WARNING From D:\tf_fcn\KittiSeg\tensorflow_fcn\fcn8_vgg.py:140: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Traceback (most recent call last):
  File "D:/tf_fcn/KittiSeg/train.py", line 134, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:/tf_fcn/KittiSeg/train.py", line 130, in main
    train.do_training(hypes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorvision\train.py", line 377, in do_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorvision\core.py", line 100, in build_training_graph
    global_step, learning_rate)
  File "D:\tf_fcn\KittiSeg\hypes\../optimizer/generic_optimizer.py", line 91, in training
    global_step=global_step)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 423, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.

Process finished with exit code 1

`

can you help me solve this problem?
thanks

**Comment by yxandam** [comment]
sorry - duplicate for #35
don't know how to delete this issue. Feel free to remove it
Sorry again
