### ISSUE TITLE
ERROR Enter URL in hypes/kittiSeg.json

### ISSUE THREAD

**Issue by wangyarui** [MarvinTeichmann/KittiSeg#134]
when I run :**python train.py --hypes hypes/KittiSeg.json**
I met this problem:

2017-10-29 13:09:13,673 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/richal/tv-plugins'.
2017-10-29 13:09:13,673 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-10-29 13:09:13,673 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-10-29 13:09:13,673 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-10-29 13:09:13,673 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-10-29 13:09:13,673 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-10-29 13:09:13,674 INFO f: <open file 'hypes/KittiSeg_VGG.json', mode 'r' at 0x7f32b1def8a0>
2017-10-29 13:09:13,687 ERROR Data URL for Kitti Data not provided.
2017-10-29 13:09:13,688 ERROR Please visit: http://www.cvlibs.net/download.php?file=data_road.zip
2017-10-29 13:09:13,688 ERROR and request Kitti Download link.
2017-10-29 13:09:13,688 ERROR Enter URL in hypes/kittiSeg.json

And I do not why took place it?Please,help.Thank U

**Comment by daixiaogang** [comment]
you can download data first and put it into  the file DATA

**Comment by wangyarui** [comment]
@daixiaogang Hi, thanks for u very much. and i appreciated you so much .but i met the other problem..by this when i run **tv-analyze --logdir ../KittiSeg_pretrained**

tv-analyze --logdir ../KittiSeg_pretrained
2017-11-29 16:24:29,988 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/richal/tv-plugins'.
2017-11-29 16:24:29,988 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-11-29 16:24:29,988 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-11-29 16:24:29,988 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-11-29 16:24:29,988 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-11-29 16:24:29,988 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-11-29 16:24:29,989 INFO Starting to analyze model in '../KittiSeg_pretrained'
2017-11-29 16:24:29,989 INFO f: <open file '../KittiSeg_pretrained/model_files/hypes.json', mode 'r' at 0x7f86cfa9d930>
Traceback (most recent call last):
  File "/usr/local/bin/tv-analyze", line 4, in <module>
    __import__('pkg_resources').run_script('tensorvision==0.1.dev1', 'tv-analyze')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tensorvision-0.1.dev1-py2.7.egg/EGG-INFO/scripts/tv-analyze", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorvision-0.1.dev1-py2.7.egg/tensorvision/analyze.py", line 476, in main
    do_analyze(FLAGS.logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorvision-0.1.dev1-py2.7.egg/tensorvision/analyze.py", line 62, in do_analyze
    modules = utils.load_modules_from_logdir(logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorvision-0.1.dev1-py2.7.egg/tensorvision/utils.py", line 215, in load_modules_from_logdir
    arch = imp.load_source("arch_%s" % postfix, f)
  File "../KittiSeg_pretrained/model_files/architecture.py", line 5, in <module>
    from tensorflow_fcn import fcn8_vgg
ImportError: No module named tensorflow_fcn

How can I import tf_fcn?

**Comment by daixiaogang** [comment]
Have you do all the steps on the author's readme.md? I am not very famiaiar with python,this is caused by the module is not properly installed. I did not meet this problem,are you interested in KittiSeg? My QQ is 750930459,you can add me and we can communicate.

**Comment by daixiaogang** [comment]
@wangyarui ,Have you do all the steps on the author's readme.md? I am not very famiaiar with python,this is caused by the module is not properly installed. I did not meet this problem,are you interested in KittiSeg? My QQ is 750930459,you can add me and we can communicate.

**Comment by SummerHuiZhang** [comment]
@daixiaogang Thank you for your method. However, I still face the same problem even I have moved road_data.zip to DATA folder and unzip it.
May I ask if you have some other methods? Besides, I have added your QQ if it's convenient for you.

**Comment by SummerHuiZhang** [comment]
I checked json file about url.    It shows like 2 lines below:
"vgg_url": "ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy",
"kitti_url": ""
The kitti_url is also empty in my workmates' KittiSeg.json file. Is that OK or something missed?

**Comment by SummerHuiZhang** [comment]
I have solved with help of Dai @daixiaogang . We should kept vgg.npy in two folders, KittiSeg/DATA and KittiSeg/DATA/wights as said in code kitti_seg_input.py.

**Comment by wangyarui** [comment]
@daixiaogang OK,thank you very much!

**Comment by wangyarui** [comment]
@SummerHuiZhang I will try your method later,thank you very much ,you are so kind and hot-hearted!
