### ISSUE TITLE
Cannot train my own data

### ISSUE THREAD

**Issue by skyuniversee** [MarvinTeichmann/KittiSeg#145]
I change the train.txt val.txt test.txt, and set my own data, but the program got this error

Traceback (most recent call last):
  File "F:/test/KittiSeg/train.py", line 131, in <module>
    tf.app.run()
  File "E:\ANACONDA\envs\python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:/test/KittiSeg/train.py", line 127, in main
    train.do_training(hypes)
  File "incl\tensorvision\train.py", line 395, in do_training
    run_training(hypes, modules, tv_graph, tv_sess)
  File "incl\tensorvision\train.py", line 288, in run_training
    hypes, sess, tv_graph['image_pl'], tv_graph['inf_out'])
  File "F:\test\KittiSeg\hypes\..\evals\kitti_eval.py", line 71, in evaluate
    image_file, gt_file = datum.split(" ")
ValueError: not enough values to unpack (expected 2, got 1)

is there anyone who also came across this question and know how to solve it?

**Comment by mmejeras** [comment]
The error means the rows in your files cannot be split properly. Do your files contain only one column of data? e.g.:
/img/img1.jpg
/img/img2.jpg

They should contain the image and gt image pair in one row as follows:

/img/img1.jpg /gt/gt1.png
/img/img2.jpg /gt/gt2.png

**Comment by skyuniversee** [comment]
I have found the problem that is there shouldn't be any new line at the end of train.txt val.txt and test.txt

**Comment by devimonica** [comment]
> 
> 
> I have found the problem that is there shouldn't be any new line at the end of train.txt val.txt and test.txt

This worked for me. Thank you so much.
