### ISSUE TITLE
ERROR:_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by zyh0904** [MarvinTeichmann/KittiSeg#176]
hello , Thank you so much for sharing your work.  But i had a problem running the code. The code that would have worked properly suddenly had the following problems when it was opened.

Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    tf.app.run()
  File "E:\Anaconda\anaconda_install\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "demo.py", line 148, in main
    image=image)
  File "incl\tensorvision\core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS\KittiSeg_pretrained\model_files\architecture.py", line 23, in inference
    vgg_fcn = fcn8_vgg.FCN8VGG(vgg16_npy_path=vgg16_npy_path)
  File "F:\KittiSeg\incl\tensorflow_fcn\fcn8_vgg.py", line 33, in __init__
    self.data_dict = np.load(vgg16_npy_path, encoding='latin1').item()
  File "E:\Anaconda\anaconda_install\lib\site-packages\numpy\lib\npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "E:\Anaconda\anaconda_install\lib\site-packages\numpy\lib\format.py", line 647, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by zyh0904** [comment]
or where can modify the `image_iter` ?

**Comment by raozhongyu** [comment]
Do you solve the problem

**Comment by zyh0904** [comment]
yes.
My vgg16.m is damaged, I download another one... :P
