### ISSUE TITLE
Can not download pretrained model ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip

### ISSUE THREAD

**Issue by mixml** [MarvinTeichmann/KittiSeg#189]
python demo.py --input_image data/demo/demo.png
2018-08-22 10:23:51,453 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/mlin2/tv-plugins'.
2018-08-22 10:23:51,453 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2018-08-22 10:23:51,454 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2018-08-22 10:23:51,454 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2018-08-22 10:23:51,454 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2018-08-22 10:23:51,454 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2018-08-22 10:23:51,454 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip
2018-08-22 10:23:51,454 INFO Download DIR: RUNS
Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    tf.app.run()
  File "/home/mlin2/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 125, in main
    maybe_download_and_extract(runs_dir)
  File "demo.py", line 88, in maybe_download_and_extract
    download_name = tv_utils.download(weights_url, runs_dir)
  File "incl/tensorvision/utils.py", line 48, in download
    reporthook=_progress)
  File "/home/mlin2/anaconda2/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/mlin2/anaconda2/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/mlin2/anaconda2/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/mlin2/anaconda2/lib/python2.7/urllib.py", line 558, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/home/mlin2/anaconda2/lib/python2.7/urllib.py", line 906, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/home/mlin2/anaconda2/lib/python2.7/ftplib.py", line 339, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/home/mlin2/anaconda2/lib/python2.7/ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "/home/mlin2/anaconda2/lib/python2.7/ftplib.py", line 222, in getresp
    raise error_temp, resp
IOError: [Errno ftp error] 425 Possible PASV port theft, cannot open data connection.

**Comment by hongq123** [comment]
Hi,have you solved this problem?

**Comment by firesnow1234** [comment]
have you solved this problem?

**Comment by HelloZEX** [comment]
Pay attention to this URL: [ftp://mi.eng.cam.ac.uk/pub/mttt2/models/](url)
download KittiSeg_pretrained.zip from your browser.  Size 2.6 GB.

**Comment by HelloZEX** [comment]
copy url to search box
