### ISSUE TITLE
error  in running  demo.py , TimeoutError and URLError

### ISSUE THREAD

**Issue by firesnow1234** [MarvinTeichmann/KittiSeg#192]
C:\Users\Yu\KittiSeg>python demo.py --input_image data/demo/demo.png
C:\Users\Yu\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-21 16:13:35,627 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to 'C:\Users\Yuki/tv-plugins'.
2018-11-21 16:13:35,627 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2018-11-21 16:13:35,627 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2018-11-21 16:13:35,627 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2018-11-21 16:13:35,627 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2018-11-21 16:13:35,627 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2018-11-21 16:13:35,627 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip
2018-11-21 16:13:35,627 INFO Download DIR: RUNS
Traceback (most recent call last):
  File "C:\Users\Yu\Anaconda3\lib\urllib\request.py", line 1541, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "C:\Users\Yu\Anaconda3\lib\urllib\request.py", line 2406, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "C:\Users\Yu\Anaconda3\lib\ftplib.py", line 361, in ntransfercmd
    source_address=self.source_address)
  File "C:\Users\YuAnaconda3\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Yu\Anaconda3\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

Have someone solved the problem, or the ftp site is down ?

Thanks

**Comment by firesnow1234** [comment]
could someone has solved this problem?

**Comment by elioexe** [comment]
How did you solve this issue ?
