### ISSUE TITLE
I got an error when running 'train.py'

### ISSUE THREAD

**Issue by namedysx** [MarvinTeichmann/KittiSeg#195]
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    tf.app.run()
  File "D:\anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 127, in main
    train.do_training(hypes)
  File "incl\tensorvision\train.py", line 377, in do_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "incl\tensorvision\core.py", line 100, in build_training_graph
    global_step, learning_rate)
  File "D:\project\KittiSeg\hypes\../optimizer/generic_optimizer.py", line 91, in training
    global_step=global_step)
  File "D:\anaconda\lib\site-packages\tensorflow\python\training\optimizer.py", line 451, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.

**Comment by mmejeras** [comment]
https://github.com/MarvinTeichmann/KittiSeg/issues/35

**Comment by namedysx** [comment]
> #35
Hi!
Thanks for your reply! I want to use tensorflow-gpu, but Python2.7 does not support tensorflow-gpu in Windows. How should I do?

**Comment by namedysx** [comment]
I have solved this problem with pull/116
