### ISSUE TITLE
Unable to train my own dataset

### ISSUE THREAD

**Issue by devimonica** [MarvinTeichmann/KittiSeg#205]
I want to train this model with my own data set. But when I tried, I got this error. Please help. @MarvinTeichmann 
`2020-04-01 14:34:40,115 INFO Step 0/20: loss = 0.38; lr = 1.00e-05; 0.123 sec (per Batch); 8.1 imgs/sec
2020-04-01 14:34:41,482 INFO       (raw)  Acc. : nan, xentropy: 0.00, weight_loss: 0.38
2020-04-01 14:34:41,484 INFO    (smooth)  Acc. : nan, xentropy: 0.00, weight_loss: 0.38
2020-04-01 14:35:49,870 INFO Running Evaluation Script.
C:\Users\devim\Mask2\KittiSeg\incl\seg_utils\seg_utils.py:119: RuntimeWarning: invalid value encountered in true_divide
  recall = totalTP / float( totalPosNum )
C:\Users\devim\Mask2\KittiSeg\incl\seg_utils\seg_utils.py:120: RuntimeWarning: invalid value encountered in true_divide
  TNR    = totalTN / float( totalNegNum )
C:\Users\devim\Mask2\KittiSeg\incl\seg_utils\seg_utils.py:123: RuntimeWarning: invalid value encountered in true_divide
  accuracy = (totalTP + totalTN) / (float( totalPosNum ) + float( totalNegNum ))
C:\Users\devim\Mask2\KittiSeg\incl\seg_utils\seg_utils.py:135: RuntimeWarning: invalid value encountered in greater_equal
  ind = np.where(recall>=i)
2020-04-01 14:37:05.160095: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\kernels\queue_base.cc:277] _0_Queues/fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 127, in main
    train.do_training(hypes)
  File "incl\tensorvision\train.py", line 395, in do_training
    run_training(hypes, modules, tv_graph, tv_sess)
  File "incl\tensorvision\train.py", line 288, in run_training
    hypes, sess, tv_graph['image_pl'], tv_graph['inf_out'])
  File "C:\Users\devim\Mask2\KittiSeg\hypes\../evals/kitti_eval.py", line 135, in evaluate
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Queues/fifo_queue, _arg_Placeholder_1_0_0, _arg_Placeholder_2_0_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\devim\Mask2\KittiSeg\hypes\../inputs/kitti_seg_input.py", line 351, in enqueue_loop
    sess.run(enqueue_op, feed_dict=make_feed(d))
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Queues/fifo_queue, _arg_Placeholder_1_0_0, _arg_Placeholder_2_0_1)]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "train.py", line 131, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 127, in main
    train.do_training(hypes)
  File "incl\tensorvision\train.py", line 392, in do_training
    modules['input'].start_enqueuing_threads(hypes, queue, 'train', sess)
  File "C:\Users\devim\Mask2\KittiSeg\hypes\../inputs/kitti_seg_input.py", line 353, in start_enqueuing_threads
    enqueue_op = q.enqueue((image_pl, label_pl))
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 338, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3202, in _queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\MaskRCNN2\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Queues/fifo_queue, _arg_Placeholder_1_0_0, _arg_Placeholder_2_0_1)]]

    total_posnum, total_negnum, total_fn, total_fp, thresh=thresh)
  File "C:\Users\devim\Mask2\KittiSeg\incl\seg_utils\seg_utils.py", line 138, in pxEval_maximizeFMeasure
    pmax = max(precision[ind])
ValueError: max() arg is an empty sequence`

**Comment by devimonica** [comment]
I resolved it by myself. So closing this issue.

**Comment by zzkslam** [comment]
Can you tell me how to solve this problem?
