### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DATA\\data_road/val3.txt'

### ISSUE THREAD

**Issue by baidut** [MarvinTeichmann/KittiSeg#24]
Run: `python evaluate.py` to evaluate the pretrained model

```
2017-03-15 08:05:37,981 INFO Graph loaded succesfully. Starting evaluation.
2017-03-15 08:05:37,981 INFO Output Images will be written to: RUNS\KittiSeg_pretrained\analyse\images/
Traceback (most recent call last):
  File "evaluate.py", line 122, in <module>
    tf.app.run()
  File "D:\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "evaluate.py", line 110, in main
    ana.do_analyze(logdir)
  File "incl\tensorvision\analyze.py", line 94, in do_analyze
    hypes, sess, image_pl, inf_out)
  File "RUNS\KittiSeg_pretrained\model_files\eval.py", line 61, in evaluate
    with open(data_file) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'DATA\\data_road/val3.txt'
```

**Comment by MarvinTeichmann** [comment]
This is a Windows path error. You can the file `val3.txt` in the folder `data`.  And the script `download_data` should have copied `val3.txt` to the right location (line 133).

My guess would be, that you are able to fix this, by adjusting the paths in [hypes/kittiseg.json](https://github.com/MarvinTeichmann/KittiSeg/blob/master/hypes/KittiVGG.json) to comply with Windows path notation (line 14).

Other then that, I would strongly recommend using Linux for deep learning ;).

**Comment by baidut** [comment]
Thank you

For windows users, please copy 
`$KITTISEG/DATA/val3.txt` to `$KITTISEG/DATA/data_road/val3.txt`
`$KITTISEG/DATA/testing.txt` to `$KITTISEG/DATA/data_road/testing.txt`

Now both the demo and evaluate works fine ( **Window 10 TensorFlow 1.0 cuda8.0 cudnn v5.1 python3.5**)

- [x] python demo.py --input_image data/demo/demo.png
- [x] python evaluate.py
