### ISSUE TITLE
When I run python demo.py --input_image data/demo.png,I got EOFError

### ISSUE THREAD

**Issue by jiaxiaotian** [MarvinTeichmann/KittiSeg#27]
Hi,Ithanks for your share of code first.When I run python demo.py --input_image data/demo.png,I got EOFError.

2017-03-27 20:57:48,990 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/tian/tv-plugins'.
2017-03-27 20:57:48,990 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-03-27 20:57:48,990 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-03-27 20:57:48,990 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-03-27 20:57:48,990 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-03-27 20:57:48,990 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-03-27 20:57:48,991 INFO f: <open file 'RUNS/KittiSeg_pretrained/model_files/hypes.json', mode 'r' at 0x7f96c3d785d0>
2017-03-27 20:57:48,991 INFO Hypes loaded successfully.
2017-03-27 20:57:48,992 INFO Modules loaded successfully. Starting to build tf graph.
Traceback (most recent call last):
  File "demo.py", line 216, in <module>
    tf.app.run()
  File "/home/tian/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 147, in main
    image=image)
  File "incl/tensorvision/core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS/KittiSeg_pretrained/model_files/architecture.py", line 23, in inference
    vgg_fcn = fcn8_vgg.FCN8VGG(vgg16_npy_path=vgg16_npy_path)
  File "/home/tian/a/KittiSeg-master/incl/tensorflow_fcn/fcn8_vgg.py", line 33, in __init__
    self.data_dict = np.load(vgg16_npy_path, encoding='latin1').item()
  File "/home/tian/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 406, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/tian/anaconda2/lib/python2.7/site-packages/numpy/lib/format.py", line 637, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

I don't know what should I do.Looking forward to your answer.Thank you very much.

**Comment by jiaxiaotian** [comment]
I found that I downloaded half of the vgg16.npy. Now the demo.py can work.

**Comment by SpearBorge** [comment]
where should the vgg16.npy put? I have downloaded it but also met the same problem...
