### ISSUE TITLE
Problems loading Resnet

### ISSUE THREAD

**Issue by jbrozena22** [MarvinTeichmann/KittiSeg#30]
I'm running into an issue where the model works great when using VGG, however fails to load the weights properly for Resnet. 

I downloaded the Resnet 101 checkpoint file from here: https://github.com/tensorflow/models/tree/master/slim#pre-trained-models

Then placed it under KittiSeg/DATA/weights/tensorflow_resnet/ResNet-L101.ckpt

But when I run this:
`python train.py --hypes hypes/KittiSeg_ResNet.json`

I get the following error:
`NotFoundError (see above for traceback): Tensor name "scale4/block11/b/moving_variance" not found in checkpoint files DATA/weights/tensorflow_resnet/ResNet-L101.ckpt`

Any idea why this wouldn't be working, or tips on finding a different set of Resnet weights that would work with this project? Thanks so much.

**Comment by MarvinTeichmann** [comment]
Use VGG for now. VGG converges much more stable and faster and all the batch_norm stuff causes more harm then good when using low batch sizes. I will push an update once I have ResNet working stable

**Comment by jbrozena22** [comment]
Ok, thanks for your help.

**Comment by ntajbakhsh** [comment]
I wonder if you guys have made any progress on this issue?

**Comment by MarvinTeichmann** [comment]
For reference, the weights can be found here: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/tensorflow_resnet/

**Comment by kalanityL** [comment]
I used Resnet and it worked. 
Issue when I try to run tests. To simplify the issue, I updated the demo.py file changing the 
default_run = 'testResnet' # (RUNS/testResnet has the ckpt of my train with Resnet. )

There is an error while building the inference graph
`ValueError: Shape of a new variable (scale1/weights) must be fully defined, but instead was (7, 7, ?, 64).`

Error comes from `_conv` of the architecture.py
`def _conv(x, filters_out, ksize=3, stride=1):
    filters_in = x.get_shape()[-1]
    shape = [ksize, ksize, filters_in, filters_out]
    initializer = tf.truncated_normal_initializer(stddev=CONV_WEIGHT_STDDEV)
    weights = _get_variable('weights',
                            shape=shape,
                            dtype='float',
                            initializer=initializer,
                            weight_decay=CONV_WEIGHT_DECAY)
    return tf.nn.conv2d(x, weights, [1, stride, stride, 1], padding='SAME')`

filters_in gets value "?" 
and it seems that is what is making the inference graph to crash

Any idea what is happening wrong? 

Full error: 
`Traceback (most recent call last):
  File "demo.py", line 228, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 148, in main
    image=image)
  File "incl/tensorvision/core.py", line 137, in build_inference_graph
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS/testResnet/model_files/architecture.py", line 72, in inference
    x = _conv(x, 64, ksize=7, stride=2)
  File "RUNS/testResnet/model_files/architecture.py", line 322, in _conv
    weight_decay=CONV_WEIGHT_DECAY)
  File "RUNS/testResnet/model_files/architecture.py", line 308, in _get_variable
    trainable=trainable)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 763, in _get_single_variable
    "but instead was %s." % (name, shape))
ValueError: Shape of a new variable (scale1/weights) must be fully defined, but instead was (7, 7, ?, 64).
`
