### ISSUE TITLE
IndexError: index 320 is out of bounds for axis 0 with size 320

### ISSUE THREAD

**Issue by FrederikHaa** [MarvinTeichmann/KittiSeg#32]
Hello,

I've been trying to train your KittiSeg network on some cell data.
I've taken the following steps to convert the network for my data:

- changed the hypes image size
- changed hypes background/foreground color
- replaced the maybe_download_and_extract function

The network trains as it is supposed to, but when it runs the evaluation script, I get the following error:

```
/gpfs/gss1/home/frhaa13/DeepBacteriaSegmentation/network/incl/seg_utils/seg_utils.py:74: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 320 but correspondin$
  fnArray = cur_prob[(gtBin == True) & (validMap == True)]
/gpfs/gss1/home/frhaa13/DeepBacteriaSegmentation/network/incl/seg_utils/seg_utils.py:82: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 320 but correspondin$
  fpArray = cur_prob[(gtBin == False) & (validMap == True)]
W tensorflow/core/kernels/queue_base.cc:294] _0_Queues/fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    tf.app.run()
  File "/gpfs/gss1/home/frhaa13/tensorenv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 129, in main
    train.do_training(hypes)
  File "incl/tensorvision/train.py", line 396, in do_training
    run_training(hypes, modules, tv_graph, tv_sess)
  File "incl/tensorvision/train.py", line 289, in run_training
    hypes, sess, tv_graph['image_pl'], tv_graph['inf_out'])
  File "/gpfs/gss1/home/frhaa13/DeepBacteriaSegmentation/network/hypes/../evals/kitti_eval.py", line 127, in evaluate
    gt_image, output_im)
  File "/gpfs/gss1/home/frhaa13/DeepBacteriaSegmentation/network/hypes/../evals/kitti_eval.py", line 34, in eval_image
    validArea=valid_gt)
  File "/gpfs/gss1/home/frhaa13/DeepBacteriaSegmentation/network/incl/seg_utils/seg_utils.py", line 82, in evalExp
    fpArray = cur_prob[(gtBin == False) & (validMap == True)]
IndexError: index 320 is out of bounds for axis 0 with size 320
```

**Comment by FrederikHaa** [comment]
Nvm, some of my pictures were the wrong resolution
