### ISSUE TITLE
EOFError when train.py

### ISSUE THREAD

**Issue by LiangTinting** [MarvinTeichmann/KittiSeg#52]
Hello Marvin,
       When I ran train.py, I met this:
2017-05-15 19:54:38,264 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/liangtingting/tv-plugins'.
2017-05-15 19:54:38,265 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-05-15 19:54:38,265 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-05-15 19:54:38,265 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-05-15 19:54:38,265 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-05-15 19:54:38,265 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-05-15 19:54:38,266 INFO f: <open file 'hypes/KittiSeg.json', mode 'r' at 0x7fe97bb2b810>
2017-05-15 19:54:38,267 INFO Initialize training folder
2017-05-15 19:54:38,303 INFO Start training
2017-05-15 19:54:38.304873: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-15 19:54:38.304906: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-15 19:54:38.304919: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 127, in main
    train.do_training(hypes)
  File "incl/tensorvision/train.py", line 377, in do_training
    tv_graph = core.build_training_graph(hypes, queue, modules)
  File "incl/tensorvision/core.py", line 85, in build_training_graph
    logits = encoder.inference(hypes, image, train=True)
  File "/home/liangtingting/KittiSeg/hypes/../encoder/fcn8_vgg.py", line 34, in inference
    vgg_fcn = fcn8_vgg.FCN8VGG(vgg16_npy_path=vgg16_npy_path)
  File "incl/tensorflow_fcn/fcn8_vgg.py", line 33, in __init__
    self.data_dict = np.load(vgg16_npy_path, encoding='latin1').item()
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 419, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/format.py", line 640, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

My tensorflow version is 1.0.1, and python  version 2.7.12. Can you help me?

**Comment by LiangTinting** [comment]
I didn't copy the whole vgg16.npy to the folder...
