### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DATA/data_road/testing.txt'

### ISSUE THREAD

**Issue by sh0416** [MarvinTeichmann/KittiSeg#80]
I run the code `python evaluate.py`, but the error occurs.
```
Traceback (most recent call last):
  File "evaluate.py", line 122, in <module>
    tf.app.run()
  File "/home/user01/anaconda2/envs/sunghyun34/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "evaluate.py", line 113, in main
    kitti_test.do_inference(logdir)
  File "incl/evaluation/kitti_test.py", line 139, in do_inference
    create_test_output(hypes, sess, image_pl, softmax)
  File "incl/evaluation/kitti_test.py", line 74, in create_test_output
    with open(data_file) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'DATA/data_road/testing.txt'
```
I check the following path, but only `testing` directory is existed and no `testing.txt` is founded. Is there any option I type when run this code????

**Comment by sh0416** [comment]
I resolve this issue, but I think it needs to be fixed.
First, RUNS directory is needed to created. I manually create one while I set up this project first.
Second, I think copying `testing.txt` from `data` directory to `DATA/data_road` directory isn't executed so that whille `python evaluate.py` raise error. I resolved this by **copying that text file manually**.

Thanks,
